apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: app-controller
          image: httpd:2.4
          ports:
            - containerPort: 80



