apiVersion: v1
kind: Service
metadata:
  name: hello-service-2
  labels:
    app: expose-service-2
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30001
      protocol: TCP
  selector:
    app: hello
    version: v3
