apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-rs-2
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello
      version: v2
  template:
    metadata:
      labels:
        app: hello
        version: v2
    spec:
      containers:
        - name: hello-controller
          image: nginx:1.13
          ports:
            - containerPort: 80
