apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    app: expose-service-1
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
      protocol: TCP
  selector:
    app: hello
